default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: crypto_bot_development
  username: crypto_bot
  password:

test:
  <<: *default
  database: crypto_bot_test
  username: crypto_bot
  password:

production:
  <<: *default
  database: crypto_bot_development
  username: crypto_bot
  password:
